### ISSUE TITLE
[LOOK] [Minor] Small white pixels on scrollbar.

### ISSUE THREAD

**Issue by horshark** [Xh4H/htb-custom-client#1]
Hey,

I noticed the little pixels in the corners of the scrollbar, only appearing if the windows is wide enough (same behavior as on the website, but on the website the background is grey/black so they don't appear).

![TOP: custom client - BOTTOM: chrome](https://cdn.discordapp.com/attachments/588029217376043023/617351956486160414/unknown.png)

**Comment by Xh4H** [comment]
Thanks for the report! I'll try to have a look at this asap :)

**Comment by Xh4H** [comment]
Fixed on a919710. Thank you!
